[package]
authors = ["Sanemat <o.gata.ken@gmail.com>"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "development-tools",
]
description = "git via https."
include = [
    "src/**/*",
    "Cargo.toml",
    "changelog.md",
    "readme.md",
    "license-apache",
    "license-mit",
]
keywords = ["git"]
license = "MIT/Apache-2.0"
name = "example"
repository = "https://github.com/packsaddle/rust-git_httpsable_cli/"
version = "0.1.0"

[[bin]]
name = "git-httpsable"
path = "src/main.rs"
[badges.appveyor]
project_name = "sanemat/rust-git-httpsable-cli"
repository = "packsaddle/rust-git_httpsable_cli"

[badges.travis-ci]
repository = "packsaddle/rust-git_httpsable_cli"

[dependencies]
