[package]
authors = ["Sanemat <o.gata.ken@gmail.com>"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "development-tools",
]
description = "My hunky-dory module"
include = [
    "src/**/*",
    "Cargo.toml",
    "changelog.md",
    "readme.md",
    "license-apache",
    "license-mit",
]
keywords = ["git"]
license = "MIT/Apache-2.0"
name = "example"
repository = "https://github.com/sanemat/example/"
version = "0.1.0"

[[bin]]
name = "example"
path = "src/main.rs"
[badges.appveyor]
project_name = "sanemat/example"
repository = "sanemat/example"

[badges.travis-ci]
repository = "sanemat/example"

[dependencies]
